container:
  image: node:10

build_task:
  clone_script: 
    - git clone --depth=50 --branch=$CIRRUS_BRANCH https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git
    - git reset --hard $CIRRUS_CHANGE_IN_REPO
  use_compute_credits: $CIRRUS_BRANCH == 'master'
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  relay_script: yarn run relay
  build_script: yarn run build

deploy_docker_builder:
  only_if: $CIRRUS_BRANCH == "master"
  depends_on: build
  environment:
    DOCKER_USER_NAME: ENCRYPTED[5eb941ed91706fab3eb53bfd01dc3b88caee18e11f9df18b4663875f83e9e390eeb0db087278035b61bf5b24e8f96328]
    DOCKER_PASSWORD: ENCRYPTED[5e9b3eb1391a7a0cf259c41920ce60d034660cc49f0b85b2738eb53d9a537b90d0d2173d6321096facd11f5e5a9e31c3]
  build_script:
    - docker --version
    - ./.ci/build_docker.sh
  push_script: ./.ci/push_docker.sh
